name: bookverse
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get: ^4.6.5
  intl: ^0.18.1
  keyboard_dismisser: ^3.0.0
  extended_image: ^7.0.2
  dio: ^5.1.1
  dartz: ^0.10.1
  lottie: ^2.3.2
  shimmer: ^2.0.0
  get_storage: ^2.1.1
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
